apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummy-rolebinding
  namespace: dummy-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dummy-role
subjects:
- kind: ServiceAccount
  name: dummy
  namespace: dummy-system
