apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dummy-role
  namespace: dummy-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
