apiVersion: v1
kind: Service
metadata:
  name: dummy-webhook-service
  namespace: dummy-system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: dummy-webhook
