
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-admissionregistration-zoetrope-github-io-v1-namespacedmutatingwebhookconfiguration
  failurePolicy: Fail
  name: mnamespacedmutatingwebhookconfiguration.kb.io
  rules:
  - apiGroups:
    - admissionregistration.zoetrope.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacedmutatingwebhookconfigurations
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-admissionregistration-zoetrope-github-io-v1-namespacedvalidatingwebhookconfiguration
  failurePolicy: Fail
  name: mnamespacedvalidatingwebhookconfiguration.kb.io
  rules:
  - apiGroups:
    - admissionregistration.zoetrope.github.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespacedvalidatingwebhookconfigurations
  sideEffects: None
