# permissions for end users to view namespacedvalidatingwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedvalidatingwebhook-viewer-role
rules:
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhooks/status
  verbs:
  - get
