# permissions for end users to view namespacedmutatingwebhookconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedmutatingwebhookconfiguration-viewer-role
rules:
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations/status
  verbs:
  - get
