# permissions for end users to view namespacedmutatingwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedmutatingwebhook-viewer-role
rules:
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhooks/status
  verbs:
  - get
