# permissions for end users to edit namespacedvalidatingwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedvalidatingwebhook-editor-role
rules:
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhooks/status
  verbs:
  - get
