# permissions for end users to edit namespacedmutatingwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedmutatingwebhook-editor-role
rules:
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhooks/status
  verbs:
  - get
