# permissions for end users to edit namespacedvalidatingwebhookconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedvalidatingwebhookconfiguration-editor-role
rules:
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations/status
  verbs:
  - get
