# permissions for end users to edit namespacedmutatingwebhookconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedmutatingwebhookconfiguration-editor-role
rules:
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations/status
  verbs:
  - get
