# permissions for end users to view namespacedvalidatingwebhookconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacedvalidatingwebhookconfiguration-viewer-role
rules:
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations/status
  verbs:
  - get
