
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfiguration
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfiguration
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedmutatingwebhookconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - webhook.zoetrope.github.io
  resources:
  - namespacedvalidatingwebhookconfigurations/status
  verbs:
  - get
  - patch
  - update
