apiVersion: webhook.zoetrope.github.io/v1
kind: NamespacedValidatingWebhookConfiguration
metadata:
  name: namespacedvalidatingwebhookconfiguration-sample
webhooks:
  - name: baseline.vpod.kb.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-baseline
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - name: restricted.vpod.kb.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-restricted
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
