apiVersion: webhook.zoetrope.github.io/v1
kind: NamespacedMutatingWebhookConfiguration
metadata:
  name: namespacedmutatingwebhookconfiguration-sample
webhooks:
  - name: baseline.mpod.kb.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-baseline
    failurePolicy: Fail
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - name: restricted.mpod.kb.io
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-restricted
    failurePolicy: Fail
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
